version: "3.9"

volumes:
    pgadmin:
    db-data:

services:
    db:
        container_name: db
        image: postgres:14
        environment:
            POSTGRES_PASSWORD: securepwd
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"