# Generated by Django 4.2 on 2023-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="qr_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
