# Generated by Django 4.2 on 2023-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_file_asset_asset_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="invoice_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
